create schema shop;

create table shop.todos (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz
);

insert into shop.todos (task) values
  ('finish tutorial 0'), ('aaaaaaaaa');


create role web_anon nologin;

grant usage on schema shop to web_anon;
grant select on shop.todos to web_anon;

create role authenticator noinherit login password 'mysecretpassword';
grant web_anon to authenticator;
