create schema shop;

create table shop.products (
  id int primary key generated by default as identity,
  name text not null,
  description text not null default '',
  available boolean not null default false,
  price numeric default null
);

insert into shop.products (name) values
  ('Speyside Line'), ('Train sim custom signs and stuff');


create role web_anon nologin;

grant usage on schema shop to web_anon;
grant select on shop.products to web_anon;

create role authenticator noinherit login password 'mysecretpassword';
grant web_anon to authenticator;
